/*Creando la base de datos*/

DROP DATABASE IF EXISTS Betisware;
CREATE DATABASE IF NOT EXISTS Betisware;
USE Betisware;


/*Creando las tablas*/

CREATE TABLE PROYECTOS(
    codProyecto int(5) NOT NULL,
    Nombre varchar(40) NOT NULL UNIQUE,
    Presupuesto_Restante decimal(12,2) NOT NULL DEFAULT 0,
    Fecha_Iniciacion date NOT NULL,
    Fecha_Limite date
);

CREATE TABLE TALLERES(
    codTaller int(3) NOT NULL,
    Estado enum('cerrado', 'abierto', 'en_mantenimiento', 'en_inspeccion') NOT NULL DEFAULT 'cerrado',
    Hora_Apertura time NOT NULL,
    Hora_Cierre time NOT NULL,
    Fecha_Inspeccion date NOT NULL
);

CREATE TABLE DIRECCIONES(
    codDireccion int(6) NOT NULL,
    Direccion varchar(40) NOT NULL UNIQUE
);

CREATE TABLE AMBITOS(
    codAmbito int(2) NOT NULL,
    Ambito varchar(40) NOT NULL UNIQUE
);

CREATE TABLE INVERSORES(
    codInversor int(3) NOT NULL,
    Nombre varchar(20),
    Apellido1 varchar(30),	
    Apellido2 varchar(30),
    Cant_Invertida decimal(11,2) NOT NULL DEFAULT 0,
    codDireccion int(6),
    Correo_Electronico varchar(30) UNIQUE,
    nTel varchar(13) UNIQUE
);

CREATE TABLE CUENTAS(
    UID int(6) NOT NULL,
    Nombre varchar(20),
    Apellido1 varchar(30),
    Apellido2 varchar(30),
    codDireccion int(6),
    Correo_Electronico varchar(30) UNIQUE,
    nTel varchar(13) UNIQUE,
    nomUsuario varchar(20) NOT NULL,
    Contraseña varbinary(255) NOT NULL
);

CREATE TABLE PERTENENCIA_AMBITOS_PROYECTOS(
    codProyecto int(5) NOT NULL,
    codAmbito int(2) NOT NULL
);

CREATE TABLE MATERIALES(
    codMaterial int(4) NOT NULL,
    Nombre varchar(100) NOT NULL,
    codTaller int(3) NOT NULL,
    Cant_Total int(4) NOT NULL DEFAULT 0,
    Cant_Disponible int(4) NOT NULL DEFAULT 0
);

CREATE TABLE INVERSIONES(
    codInversor int(3) NOT NULL,
    codProyecto int(5) NOT NULL,
    Dinero decimal(12,2) NOT NULL,
    Fecha date NOT NULL,
    Hora time NOT NULL
);

CREATE TABLE IDEAS(
    codIdea int(6) NOT NULL,
    Nombre varchar(40) NOT NULL,
    UID int(6) NOT NULL,
    Estado enum('sin_inspeccionar', 'en_inspeccion', 'en_espera', 'en_preparacion') NOT NULL DEFAULT 'sin_inspeccionar',
    Fecha_Creacion date NOT NULL,
    Puntuacion_Total int(3),
    Puntuacion_Social int(3),
    Puntuacion_Medioambiental int(3),
    Puntuacion_Economica int(3)
);

CREATE TABLE PERFILES(
    codPerfil int(2) NOT NULL,
    Perfil varchar(30) NOT NULL UNIQUE
);

CREATE TABLE PROYECTOS_TALLERES(
    codProyecto int(5) NOT NULL,
    codTaller int(3) NOT NULL,
    Fecha_Asignacion date NOT NULL,
    Horas_Invertidas decimal(6,2) NOT NULL DEFAULT 0
);

CREATE TABLE INSPIRACIONES_PROYECTOS(
    codIdea int(6) NOT NULL,
	codProyecto int(5) NOT NULL
);

CREATE TABLE EMPLEADOS(
    codEmpleado int(4) NOT NULL,
    Nombre varchar(20) NOT NULL,
    Apellido1 varchar(30) NOT NULL,
    Apellido2 varchar(30) NOT NULL,
    codSeguridad_Social int(12) NOT NULL UNIQUE,
    Fecha_Entrada date NOT NULL,
    Salario_Anual decimal(9,2) NOT NULL,
    Fecha_Nacimiento date NOT NULL,
    codPerfil int(2) NOT NULL,
    Dias_Vacaciones_Restantes int(3) NOT NULL,
    codDireccion int(6) NOT NULL,
    Correo_Electronico varchar(30) UNIQUE,
    codHuella int(4) NOT NULL UNIQUE,
    nTel varchar(13) UNIQUE
);

CREATE TABLE PROYECTOS_EMPLEADOS(
    codEmpleado int(4) NOT NULL,
    codProyecto int(5) NOT NULL,
    Fecha_Asignacion date NOT NULL,
    Horas_Invertidas decimal(6,2) NOT NULL DEFAULT 0
);

CREATE TABLE PERTENENCIA_AMBITOS_IDEAS(
    codIdea int(6),
    codAmbito int(2)
);

CREATE TABLE HUELLAS(
    codHuella int(4) NOT NULL,
    Huella varbinary(255) NOT NULL UNIQUE
);


/*Creando las primary keys*/

ALTER TABLE DIRECCIONES ADD CONSTRAINT PK_DIRECCIONES PRIMARY KEY (codDireccion);
ALTER TABLE PROYECTOS ADD CONSTRAINT PK_PROYECTOS PRIMARY KEY (codProyecto);
ALTER TABLE AMBITOS ADD CONSTRAINT PK_AMBITOS PRIMARY KEY (codAmbito);
ALTER TABLE TALLERES ADD CONSTRAINT PK_TALLERES PRIMARY KEY (codTaller);
ALTER TABLE INVERSORES ADD CONSTRAINT PK_INVERSORES PRIMARY KEY (codInversor);
ALTER TABLE CUENTAS ADD CONSTRAINT PK_CUENTAS PRIMARY KEY (UID);
ALTER TABLE PERTENENCIA_AMBITOS_PROYECTOS ADD CONSTRAINT PK_PERTENENCIA_AMBITOS_PROYECTOS PRIMARY KEY (codProyecto, codAmbito);
ALTER TABLE MATERIALES ADD CONSTRAINT PK_MATERIALES PRIMARY KEY (codMaterial);
ALTER TABLE INVERSIONES ADD CONSTRAINT PK_INVERSIONES PRIMARY KEY (codInversor, codProyecto);
ALTER TABLE IDEAS ADD CONSTRAINT PK_IDEAS PRIMARY KEY (codIdea);
ALTER TABLE PERFILES ADD CONSTRAINT PK_PERFILES PRIMARY KEY (codPerfil);
ALTER TABLE PROYECTOS_TALLERES ADD CONSTRAINT PK_PROYECTOS_TALLERES PRIMARY KEY (codTaller, codProyecto);
ALTER TABLE INSPIRACIONES_PROYECTOS ADD CONSTRAINT PK_INSPIRACIONES_PROYECTOS PRIMARY KEY (codIdea, codProyecto);
ALTER TABLE EMPLEADOS ADD CONSTRAINT PK_EMPLEADOS PRIMARY KEY (codEmpleado);
ALTER TABLE PROYECTOS_EMPLEADOS ADD CONSTRAINT Pk_PROYECTOS_EMPLEADOS PRIMARY KEY (codEmpleado, codProyecto);
ALTER TABLE PERTENENCIA_AMBITOS_IDEAS ADD CONSTRAINT PK_PERTENENCIA_AMBITOS_IDEAS PRIMARY KEY (codIdea, codAmbito);
ALTER TABLE HUELLAS ADD CONSTRAINT PK_HUELLAS PRIMARY KEY (codHuella);


/*Creando las foreign keys*/

ALTER TABLE INVERSORES ADD CONSTRAINT FK_INVERSORES_direcciones FOREIGN KEY (codDireccion) REFERENCES DIRECCIONES(codDireccion);

ALTER TABLE CUENTAS ADD CONSTRAINT FK_CUENTAS_direcciones FOREIGN KEY (codDireccion) REFERENCES DIRECCIONES(codDireccion);

ALTER TABLE PERTENENCIA_AMBITOS_PROYECTOS ADD CONSTRAINT FK_PERTENENCIA_AMBITOS_PROYECTOS_proyectos FOREIGN KEY (codProyecto) REFERENCES PROYECTOS(codProyecto);
ALTER TABLE PERTENENCIA_AMBITOS_PROYECTOS ADD CONSTRAINT FK_PERTENENCIA_AMBITOS_PROYECTOS_ambitos FOREIGN KEY (codAmbito) REFERENCES AMBITOS(codAmbito);

ALTER TABLE MATERIALES ADD CONSTRAINT FK_MATERIALES_talleres FOREIGN KEY (codTaller) REFERENCES TALLERES(codTaller);

ALTER TABLE INVERSIONES ADD CONSTRAINT FK_INVERSIONES_inversores FOREIGN KEY (codInversor) REFERENCES INVERSORES(codInversor);
ALTER TABLE INVERSIONES ADD CONSTRAINT FK_INVERSIONES_proyectos FOREIGN KEY (codProyecto) REFERENCES PROYECTOS(codProyecto);

ALTER TABLE IDEAS ADD CONSTRAINT FK_IDEAS_cuentas FOREIGN KEY (UID) REFERENCES CUENTAS(UID);

ALTER TABLE PROYECTOS_TALLERES ADD CONSTRAINT FK_PROYECTOS_TALLERES_talleres FOREIGN KEY (codTaller) REFERENCES TALLERES(codTaller);
ALTER TABLE PROYECTOS_TALLERES ADD CONSTRAINT FK_PROYECTOS_TALLERES_proyectos FOREIGN KEY (codProyecto) REFERENCES PROYECTOS(codProyecto);

ALTER TABLE INSPIRACIONES_PROYECTOS ADD CONSTRAINT FK_INSPIRACIONES_PROYECTOS_ideas FOREIGN KEY (codIdea) REFERENCES IDEAS(codIdea);
ALTER TABLE INSPIRACIONES_PROYECTOS ADD CONSTRAINT FK_INSPIRACIONES_PROYECTOS_proyectos FOREIGN KEY (codProyecto) REFERENCES PROYECTOS(codProyecto);

ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_EMPLEADOS_perfil FOREIGN KEY (codPerfil) REFERENCES PERFILES(codPerfil);
ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_EMPLEADOS_direcciones FOREIGN KEY (codDireccion) REFERENCES DIRECCIONES(codDireccion);
ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_EMPLEADOS_huellas FOREIGN KEY (codHuella) REFERENCES HUELLAS(codHuella);

ALTER TABLE PROYECTOS_EMPLEADOS ADD CONSTRAINT FK_PROYECTOS_EMPLEADOS_empleados FOREIGN KEY (codEmpleado) REFERENCES EMPLEADOS(codEmpleado);
ALTER TABLE PROYECTOS_EMPLEADOS ADD CONSTRAINT FK_PROYECTOS_EMPLEADOS_proyectos FOREIGN KEY (codProyecto) REFERENCES PROYECTOS(codProyecto);

ALTER TABLE PERTENENCIA_AMBITOS_IDEAS ADD CONSTRAINT FK_PERTENENCIA_AMBITOS_IDEAS_ideas FOREIGN KEY (codIdea) REFERENCES IDEAS(codIdea);
ALTER TABLE PERTENENCIA_AMBITOS_IDEAS ADD CONSTRAINT FK_PERTENENCIA_AMBITOS_IDEAS_ambitos FOREIGN KEY (codAmbito) REFERENCES AMBITOS(codAmbito);